name: yallabina
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^4.2.0
  flutter_pdfview: ^1.3.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  socket_io_client: ^3.1.1
  web_socket_channel: ^3.0.3
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  dartz: ^0.10.1
  intl: ^0.20.2
  dio: ^5.5.0
  mime: ^2.0.0
  shared_preferences: ^2.2.2  # إصدار مستقر لتجنب أخطاء shared_preferences_android
  get: ^4.7.2
  agora_rtc_engine: ^6.5.2
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  http: ^1.2.2
  http_parser: ^4.0.2
  introduction_screen: ^3.1.17
  flutter_svg: ^2.0.10
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/